# Generated by Django 5.2.14 on 2026-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="target_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ACCOUNT_CREATED", "Account Created"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                ],
                max_length=50,
            ),
        ),
    ]
