# Generated by Django 5.2.14 on 2026-06-03 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auditlog_target_id_auditlog_target_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
