# Generated by Django 5.2.14 on 2026-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_is_system_role_user_created_by"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="auth.permission"
            ),
        ),
    ]
